spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

jwt:
  secretKey: LeRUmTTsh6f6b2HsuaSuH3hTq6hsiXPqBr7BoAL3s+bCjtVqLuek8ByYytKvqKfc

server:
  port: ${SERVER_PORT}