config:
  paths:
    project-service: lb://project-service
    kube-service: lb://kube-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    healthcheck:
      enabled: true