spring:
  application:
    name: api-gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

jwt:
  secretKey: LeRUmTTsh6f6b2HsuaSuH3hTq6hsiXPqBr7BoAL3s+bCjtVqLuek8ByYytKvqKfc

server:
  port: 9000