config:
  paths:
    user-service: lb://user-service
    project-service: lb://project-service
    docker-registry: localhost:5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true