services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data/mongo:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q status && rabbitmq-diagnostics -q check_local_alarms
      interval: 3s
      retries: 10

  api-gateway:
    build:
      dockerfile: ./api-gateway/Dockerfile
    environment:
      ENVIRONMENT: dev-docker
    scale: 1
    ports:
      - 9000:9000
      #- 9000-9010:9000

  project-service:
    build:
      dockerfile: ./project-service/Dockerfile
    environment:
      ENVIRONMENT: dev-docker
      MONGO_URL: mongo
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    depends_on:
      mongo:
        condition: service_started

  user-service:
    build:
      dockerfile: ./user-service/Dockerfile
    environment:
      ENVIRONMENT: dev-docker
      POSTGRES_URL: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      RABBITMQ_HOST: rabbitmq
    depends_on:
      postgres:
        condition: service_started

  logs-service:
    build:
      dockerfile: ./logs-service/Dockerfile
    environment:
      LOG_PATH: logback.log
      RABBITMQ_HOST: rabbitmq
    volumes:
      - ./data/logs:/logs
    depends_on:
      rabbitmq:
        condition: service_healthy