spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo@$localhost:27017
      database: projects

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka