spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_URL}:27017
      database: projects
      auto-index-creation: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest