spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_URL}:27017
      database: projects
      auto-index-creation: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: guest
    password: guest

server:
  port: ${SERVER_PORT}