spring:
  application:
    name: Project Service
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017
      database: projects
      auto-index-creation: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081